### ISSUE TITLE
Publish SDK API to Nuget

### ISSUE THREAD

**Issue by enclave-tom** [enclave-networks/enclave.sdk.api#12]
Build process needs to publish Nuget package

**Comment by enclave-alistair** [comment]
Need to get a NuGet API token for pushing builds on main to Nuget.org.

**Comment by enclave-marc-barry** [comment]
My personal email (marc.barry@enclaveio.onmicrosoft.com) is hooked up as https://www.nuget.org/profiles/westgatecyber

We have an organisation called https://www.nuget.org/profiles/enclave owned by support@enclave.io of which the user `westgatecyber` is the sole Administrator at present

**Comment by enclave-alistair** [comment]
I've added an action secret to this repository, `NUGET_KEY`, so you can push to nuget.org from here @enclave-tom.

You can update the nuget push command like so:

```
dotnet nuget push src/**/*${{ steps.gitversion.outputs.SemVer }}.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
```

**Comment by enclave-alistair** [comment]
yep

**Comment by enclave-tom** [comment]
Documentation has been updated i'm closing this issue
